dist: bionic
cache: bundler

branches:
  only:
  - master
  - dev

language: ruby
rvm:
- 2.6.3

services:
- memcached

env:
- RAILS_ENV=test

before_script:
- sudo script/travis_prepare_db
script:
- bundle exec rake
