# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= CONFIG["secret_key_base"] || "418d4e35f163ea17124c7132440f923afda80257d232fc8f399427f9ff6fef4bdef545c39c4c0317e08d45f7b8efebe7bfcfa3ad321763b98036d4b3d5ff6e8f" %>

test:
  secret_key_base: c10353417a2e3d7447b1db3936d6832eceacc0f1af1eefb58d0d2c0e30bfde7292416d9e97fafeed998167c11fbcb08d4aa3dad1ec5cc0c6bdccc773b00afecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
